<h1>TransPhper</h1>

<p>
    A simple transfer.sh clone in PHP
</p>

<p>
    How to uplad file : <br/>
    <pre>curl --upload-file ./hello.txt https://[installed domain]/hello.txt</pre>
    
    This command display the following message to down the file :  <br/>
    <pre>Download URL : https://[installed domain]/[hash]/hello.txt</pre>

    It didn't do more (not file cleannig or anything), just upload and download.
</p>